[package]
name = "transliterator-node"
version = "0.1.0"
edition = "2021"
authors = ["Unsigned Labs"]
description = "Node.js bindings for transliterator"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
transliterator = { path = "../../core" }
napi = { version = "2", default-features = false, features = ["napi9"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
