import { TransliterationSchema } from "../types/transliteration";

export const banglaSchema: TransliterationSchema = {
  consonants: {
    ক: ["k", "K"],
    খ: ["kh", "kH", "Kh", "KH"],
    গ: ["g", "G"],
    ঘ: ["gh", "gH", "Gh", "GH"],
    ঙ: ["ng", "Ng", "NG", "nG"],
    চ: ["c", "ch"],
    ছ: ["C", "Ch", "chh", "Chh", "CHh", "CHH"],
    জ: ["j", "J"],
    ঝ: ["jh", "jH", "Jh", "JH"],
    ঞ: ["ny"],
    ট: ["T"],
    ঠ: ["Th"],
    ড: ["D"],
    ঢ: ["Dh"],
    ণ: ["N"],
    ত: ["t"],
    থ: ["th"],
    দ: ["d"],
    ধ: ["dh"],
    ন: ["n"],
    প: ["p", "P"],
    ফ: ["f", "F", "ph", "pH", "Ph", "PH"],
    ব: ["b", "B"],
    ভ: ["v", "V", "bh", "bH", "Bh", "BH"],
    ম: ["m", "M"],
    য: ["z"],
    র: ["r"],
    ল: ["l", "L"],
    শ: ["sh", "Sh", "SH", "sH"],
    ষ: ["Sh", "shh", "Shh", "SHh", "SHH"],
    স: ["s", "S"],
    হ: ["h", "H"],
    ড়: ["rr", "R", "RR", "rR", "Rr"],
    ঢ়: ["rh", "Rh", "rH", "RH"],
    য়: ["y", "Y"],
    ক্ষ: ["x", "X"],
  },
  vowels: {
    অ: ["o"],
    আ: ["a"],
    ই: ["i"],
    ঈ: ["ii", "I"],
    উ: ["u"],
    ঊ: ["uu", "U"],
    ঋ: ["ri"],
    এ: ["e"],
    ঐ: ["oi"],
    ও: ["O"],
    ঔ: ["ou"],
  },
  vowelMarks: {
    "": ["o"],
    "া": ["a"],
    "ি": ["i"],
    "ী": ["ii", "I"],
    "ু": ["u"],
    "ূ": ["uu", "U"],
    "ৃ": ["ri"],
    "ে": ["e"],
    "ৈ": ["oi"],
    "ো": ["O"],
    "ৌ": ["ou"],
  },
  specialChar: {
    "ং": ["ng", "Ng", "NG", "nG"],
    "ঃ": ["h"],
    "ঁ": ["*"],
    "্": [""],
    "।": ["|"],
  },
  digits: {
    "০": ["0"],
    "১": ["1"],
    "২": ["2"],
    "৩": ["3"],
    "৪": ["4"],
    "৫": ["5"],
    "৬": ["6"],
    "৭": ["7"],
    "৮": ["8"],
    "৯": ["9"],
  },
  exceptions: {
    specialCombinations: {
      "gy": "জ্ঞ",
      "dnyo": "জ্ঞ",
      "kkhyo": "ক্ষ্য",
    },
    joinedConsonantsBefore: {},
    joinedConsonantsAfter: {
      "w": "ব",
    },
    explicitHolonto: "্",
  },
};
