import { TransliterationSchema } from "../types/transliteration";

export const hindiSchema: TransliterationSchema = {
  consonants: {
    क: ["k", "K"],
    ख: ["kh", "kH", "Kh", "KH"],
    ग: ["g", "G"],
    घ: ["gh", "gH", "Gh", "GH"],
    ङ: ["ng", "Ng", "NG", "nG"],
    च: ["c", "ch"],
    छ: ["C", "Ch", "chh", "Chh", "CHh", "CHH"],
    ज: ["j", "J"],
    झ: ["jh", "jH", "Jh", "JH"],
    ञ: ["ny"],
    ट: ["T"],
    ठ: ["Th"],
    ड: ["D"],
    ढ: ["Dh"],
    ण: ["N"],
    त: ["t"],
    थ: ["th"],
    द: ["d"],
    ध: ["dh"],
    न: ["n"],
    प: ["p", "P"],
    फ: ["f", "F", "ph", "pH", "Ph", "PH"],
    ब: ["b", "B"],
    भ: ["v", "V", "bh", "bH", "Bh", "BH"],
    म: ["m", "M"],
    य: ["y", "Y"],
    र: ["r"],
    ल: ["l", "L"],
    व: ["w", "W"],
    श: ["sh", "Sh", "SH", "sH"],
    ष: ["Sh", "shh", "Shh", "SHh", "SHH"],
    स: ["s", "S"],
    ह: ["h", "H"],
    क्ष: ["x", "X", "ksh", "Ksh", "KSh", "KSH"],
    त्र: ["tr"],
    ज्ञ: ["gy", "dnyo"],
    ड़: ["rr", "R", "RR", "rR", "Rr"],
    ढ़: ["rh", "Rh", "rH", "RH"],
  },
  vowels: {
    अ: ["a"],
    आ: ["aa", "A"],
    इ: ["i"],
    ई: ["ii", "I"],
    उ: ["u"],
    ऊ: ["uu", "U"],
    ऋ: ["ri"],
    ए: ["e"],
    ऐ: ["ai"],
    ओ: ["o"],
    औ: ["au"],
  },
  vowelMarks: {
    "": ["a"],
    "ा": ["aa", "A"],
    "ि": ["i"],
    "ी": ["ii", "I"],
    "ु": ["u"],
    "ू": ["uu", "U"],
    "ृ": ["ri"],
    "े": ["e"],
    "ै": ["ai"],
    "ो": ["o"],
    "ौ": ["au"],
  },
  specialChar: {
    "ं": ["ng", "Ng", "NG", "nG"],
    "ः": ["h"],
    "ँ": ["*"],
    "्": [""],
    "।": ["|"],
    "॥": ["||"],
  },
  digits: {
    "०": ["0"],
    "१": ["1"],
    "२": ["2"],
    "३": ["3"],
    "४": ["4"],
    "५": ["5"],
    "६": ["6"],
    "७": ["7"],
    "८": ["8"],
    "९": ["9"],
  },
  exceptions: {
    specialCombinations: {
      "gy": "ज्ञ",
      "dnyo": "ज्ञ",
      "ksh": "क्ष",
      "tr": "त्र",
    },
    joinedConsonantsBefore: {},
    joinedConsonantsAfter: {},
    explicitHolonto: "्",
  },
};
